# Teste de modelo para o Dataset

## Importações

In [1]:
import os 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

In [23]:
CSV_DIR = os.getcwd() + "/../datasets/"
dataset = pd.read_csv(CSV_DIR + "dataset.csv")
columns = dataset.shape[1]
dataset.head()


Unnamed: 0  frame     b x     b y  ITandroids center of mass x  \
0           0      4 -1.5900 -1.3332                   -16.432536   
1           1      5 -3.0539 -2.6046                   -16.077636   
2           2      6 -4.4260 -3.7900                   -15.788364   
3           3      7 -5.6755 -4.8628                   -15.365473   
4           4      8 -6.8484 -5.8776                   -14.888573   

   ITandroids center of mass y     r1 x    r1 y     r2 x    r2 y  ...    r7 y  \
0                     0.053164 -49.4044  0.0181 -23.1131 -4.7685  ... -9.9501   
1                     0.069691 -49.4149  0.0201 -22.3576 -4.6877  ... -9.8315   
2                     0.024327 -49.4188  0.0209 -22.0105 -4.6423  ... -9.7910   
3                    -0.134573 -49.4204  0.0212 -21.5631 -4.8640  ... -9.7775   
4                    -0.359064 -49.4210  0.0213 -21.0248 -5.1935  ... -9.7732   

      r8 x     r8 y    r9 x     r9 y    r10 x   r10 y    r11 x   r11 y  \
0 -11.8610  10.6285 -1.1995 -25.0128 -49.4044  0.0181 -49.4044  0.0181   
1 -11.1785  10.4110 -1.2265 -24.6273 -49.4149  0.0201 -49.4149  0.0201   
2 -10.5076  10.1747 -1.2271 -24.4297 -49.4188  0.0209 -49.4188  0.0209   
3  -9.8383   9.9315 -0.8649 -24.4530 -49.4204  0.0212 -49.4204  0.0212   
4  -9.2193   9.6592 -0.2685 -24.6017 -49.4210  0.0213 -49.4210  0.0213   

   team name  
0          0  
1          0  
2          0  
3          0  
4          0  

[5 rows x 29 columns]

## Formação da matriz

In [24]:
previsores = dataset.iloc[:, 2:columns-1].values
classe = dataset.iloc[:, columns-1].values
previsores

array([[-1.59000000e+00, -1.33320000e+00, -1.64325364e+01, ...,
         1.81000000e-02, -4.94044000e+01,  1.81000000e-02],
       [-3.05390000e+00, -2.60460000e+00, -1.60776364e+01, ...,
         2.01000000e-02, -4.94149000e+01,  2.01000000e-02],
       [-4.42600000e+00, -3.79000000e+00, -1.57883636e+01, ...,
         2.09000000e-02, -4.94188000e+01,  2.09000000e-02],
       ...,
       [ 1.47359000e+01,  2.39510000e+01, -1.29104545e+00, ...,
         5.97600000e-01, -4.94195000e+01,  5.97600000e-01],
       [ 1.54856000e+01,  2.38745000e+01, -8.10718182e-01, ...,
         5.97600000e-01, -4.94195000e+01,  5.97600000e-01],
       [ 1.61995000e+01,  2.37857000e+01, -2.79863636e-01, ...,
         5.97600000e-01, -4.94195000e+01,  5.97600000e-01]])

## Transformar o nome dos times em variáveis numéricas

In [25]:
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
labelencoder.inverse_transform([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [26]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(
                                                    previsores,
                                                    classe,
                                                    test_size = 0.3,
                                                    random_state = 0
                                                    )


## Naive Bayes

In [18]:
naive_bayes = GaussianNB()
naive_bayes.fit(x_treinamento, y_treinamento)
x_i = x_treinamento[y_treinamento==1, :]

In [20]:
previsoes = naive_bayes.predict(x_teste)
from sklearn.metrics import classification_report

In [21]:
confusao = confusion_matrix(y_teste, previsoes)
confusao

array([[42, 35, 59,  4, 14],
       [ 5, 51, 66,  2, 23],
       [22, 29, 59,  7, 29],
       [21, 40, 45, 19, 16],
       [28, 29, 51,  0, 54]])

In [22]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_erro = 1 - taxa_acerto
taxa_acerto

0.3

In [10]:
import convert.bayes as bayes
cmodel = bayes.Convert(naive_bayes)
cmodel.save(file='coach_model.h')

[[ 1.79565217e+01 -4.71982415e+00 -4.17419082e+00 -4.94511507e+01
  -4.77275362e-02 -1.75563643e+01 -5.95093961e+00 -1.72758932e+01
   3.85788406e+00 -1.68141019e+01 -1.70151618e+01 -1.68627188e+01
   1.52512208e+01 -9.62843430e+00 -6.21684541e-01 -6.93954058e+00
  -9.85720725e+00 -5.43047150e+00  8.92995749e+00  4.07205556e+00
  -2.44117821e+01 -4.94511507e+01 -4.77275362e-02 -4.94511507e+01
  -4.77275362e-02]
 [ 1.86666667e+01 -4.98098213e+00 -3.82185990e-01 -4.95004758e+01
   1.99170048e-01 -1.75420208e+01 -4.86027246e+00 -1.73114807e+01
   5.03460918e+00 -1.63624928e+01 -1.59035068e+01 -1.63679435e+01
   1.62913556e+01 -9.72635749e+00  4.65100966e-01 -6.05356329e+00
  -9.36662367e+00 -6.54567295e+00  8.89250676e+00  4.06416860e+00
  -2.34524106e+01 -4.95004758e+01  1.99170048e-01 -4.95004758e+01
   1.99170048e-01]
 [ 1.86190476e+01 -5.40732143e+00 -2.87692286e+00 -4.94779552e+01
  -1.31230476e-01 -1.74027676e+01 -5.74707238e+00 -1.74797957e+01
   4.14021571e+00 -1.67272614e+01 -1.6

## K Neighbors 

In [27]:
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(x_treinamento, y_treinamento)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [28]:
y_pred = neigh.predict(x_teste)

(2, 63, 26)


In [48]:
import convert.neighbors as neighbors
cmodel = neighbors.Convert(x_treinamento, y_treinamento)
cmodel.save(file='coach_model.h')

In [29]:
confusao = confusion_matrix(y_teste, y_pred)
confusao

array([[137,   4,   1,   9,   3],
       [  2, 131,   5,   7,   2],
       [  3,   2, 136,   2,   3],
       [  4,   2,   0, 132,   3],
       [  8,   6,   4,   4, 140]])

In [30]:
taxa_acerto = accuracy_score(y_teste, y_pred)
taxa_erro = 1 - taxa_acerto
taxa_acerto

0.9013333333333333